---
title: "Getting and Cleaning Data Course Project Codebook"
output: html_document
---

##About the Data
###Human Activity Recognition Using Smartphones Dataset

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained data set has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 


For each record it is provided:
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.  
- Triaxial Angular velocity from the gyroscope.   
- A 561-feature vector with time and frequency domain variables.   
- Its activity label.   
- An identifier of the subject who carried out the experiment.  

The dataset includes the following files:  
- 'README.txt'  
- 'features_info.txt': Shows information about the variables used on the feature vector.  
- 'features.txt': List of all features.  
- 'activity_labels.txt': Links the class labels with their activity name.  
- 'train/X_train.txt': Training set.  
- 'train/y_train.txt': Training labels.  
- 'test/X_test.txt': Test set.  
- 'test/y_test.txt': Test labels.  

The following files are available for the train and test data. Their descriptions are equivalent.   
- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.   

'features_info.txt': Shows information about the variables used on the feature vector.  
'features.txt': List of all features.  

- Features are normalized and bounded within [-1,1].  
- Each feature vector is a row on the text file.  

##Project Requirement
1.Merges the training and the test sets to create one data set.  
2.Extracts only the measurements on the mean and standard deviation for each measurement  
3.Uses descriptive activity names to name the activities in the data set  
4.Appropriately labels the data set with descriptive variable names.  
5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject  

##Project Steps
Note: 
Detailed R codes are not embeded in this code book.Please find specific code in ranAnalysis.R attachment.  

####1.Merges the training and the test sets to create one data set
* Download the data set  
* Set the working directory  
* Load useful libraries  
* Read in data including features, Train and Test data  
* Assign column names for subject, activity and measurement (features)  
* Combine columns for train set using cbind  
* combine columns for test set using cbind  
* Merge both train and test sets using rbind  

####2.Extracts only the measurements on the mean and standard deviation for each measurement.
* Use grepl function to keep columns of subject and activity 
* and separate mean and standard deviation measurement variables from the rest  
* keep only the variables of interests   

####3.Uses descriptive activity names to name the activities
* Read in activity_labels data  
* Use gsub function to rename the activity types  
* Use label function to check the new activity labels  

####4.Appropriately labels the data set with descriptive variable names
* Use name function to check the current column names to identify variable names to be revised  
* Use gsub function to clean up names and rename variable with more descriptive names   

####5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject
* Use melt function to melt down the current merged and relabeled data, id subject and activity for later grouping  
* Use dcast to find group means at the combination of subject and activity level  
* Use dim, names and head functions to check the results  
* The alternative approach for the group means per request could be using the ddply function from dply  
* Use write.table function to write the tidy data  